/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.hajo.jsfs.bb;

import edu.chl.hajo.jsfs.mb.ShopBean;
import edu.chl.hajo.shop.core.Product;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;

/**
 *
 * @author hajo
 */
@Named("addProduct")
@RequestScoped  // NOTE enterprise package, else disaster!!!
public class AddProductBB {
    
    @NotNull(message="{common.notEmpty}")
    @Pattern(regexp="[a-zA-Z0-9]{4,20}", message="{product.name}")
    private String name;
    
    @NotNull(message="{common.notEmpty}")
    @DecimalMax(value="100000", message="{product.price}")
    @DecimalMin(value="0", message="{product.price}")
    @Digits(integer=6, fraction=2, message="{product.price}")
    private String price;
    
    
    private ShopBean shop;

    public String save() {
        // Id generated by database
        System.out.print("Entering save in add.");
        System.out.print("price validated.");
        Product p = new Product(name, Double.valueOf(price));
        shop.getProductCatalogue().add(p);
        return Navigation.PRODUCT_SUCCESS.toString();  // TODO
    }
    @Inject
    public void initMB(){
         shop = ShopBean.getInstance();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }
}
